run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - ineffassign
    - typecheck

issues:
  exclude-dirs:
    - pkg/image
    - pkg/lifecycle
    - test/e2e
    - test/integration